Beginner and Library Usage Assignment
applibgroup/assessment pull request #27
Opened 2021-05-31 14:51 UTC by cs1180369

2021-06-01 20:24 UTC, cs1180369 commented
Added HarmonyOS Day 1 assignment

2021-06-02 20:57 UTC, kanaksony requested changes
Please resolve the requested feedback.

2021-06-02 20:57 UTC, kanaksony commented on Android/PulaJaswanthRam/Beginner/SplashScreen/app/src/main/java/com/example/splashscreen/MainActivity.java
> +        mSlide = (ViewPager) findViewById(R.id.slide);
Please avoid redundancy. Casting to views needs to be optimized.

2021-06-02 20:57 UTC, kanaksony commented on Android/PulaJaswanthRam/Beginner/SplashScreen/app/src/main/java/com/example/splashscreen/MainActivity.java
> +        nBtn.setOnClickListener(new View.OnClickListener() {
Try to use lambdas in place of anonymous inner listeners all over the code.

2021-06-02 20:57 UTC, kanaksony commented on Android/PulaJaswanthRam/Beginner/SplashScreen/app/src/main/java/com/example/splashscreen/SliderAdapter.java
> +    public String[] slide_desc = {
Move string text to strings.xml under resources

2021-06-02 20:57 UTC, kanaksony commented on Android/PulaJaswanthRam/Beginner/SplashScreen/app/src/main/java/com/example/splashscreen/SliderAdapter.java
> +    public boolean isViewFromObject(View view, Object object) {
Handle nullability by annotating parameters as @NonNull. Check casting redundancy all over and clean code.

2021-06-02 20:57 UTC, kanaksony commented on Android/PulaJaswanthRam/Intermediate/ToDoApplication/app/src/main/java/com/example/todoapplication/WelcomePage.java
> +        Handler handler = new Handler();
The handler is deprecated. Use the recommendation and try using lambda in place of Anonymous new Runnable().

2021-06-02 20:57 UTC, kanaksony commented on Android/PulaJaswanthRam/Intermediate/ToDoApplication/app/src/main/java/com/example/todoapplication/WelcomePage.java
> +        actionBar.hide();
Handle nullpointerexception

2021-06-02 20:57 UTC, kanaksony commented on Android/PulaJaswanthRam/Intermediate/ToDoApplication/app/src/main/java/com/example/todoapplication/Adapter/ToDoAdapter.java
> +    public class MyViewHolder extends RecyclerView.ViewHolder{
Declare Inner class 'MyViewHolder' with 'static'  to avoid Memory leaks.

2021-06-04 19:06 UTC, cs1180369 commented
All changes made according to requests

2021-06-04 19:07 UTC, cs1180369 commented on Android/PulaJaswanthRam/Intermediate/ToDoApplication/app/src/main/java/com/example/todoapplication/WelcomePage.java
> +        actionBar.hide();
Done

2021-06-21 04:41 UTC, kanaksony approved these changes

2021-06-21 04:42 UTC, merged